(FEAT)[#12] Add ViewModelStore.
android-alatan/LifecycleComponents pull request #14
Opened 2023-02-11 12:38 UTC by taehwandev

ViewModelStore 추가.
activate() 시점에 ViewModelStore에 추가

```
private val viewModel = ComposeSampleViewModel(this)

@Composable
    override fun contentView() {
        viewModel.activate()
 
       Column {
            HelloWorld1()
        }
    }

@Composable
fun HelloWorld1(composeSampleViewModel: ComposeSampleViewModel = lifecycleViewModel()) {
}
```

2023-02-11 13:54 UTC, SeongUgJung requested changes

2023-02-11 13:54 UTC, SeongUgJung commented on _lifecycle-handler/_compose/lifecycle-handler-compose-util/src/main/java/io/androidalatan/lifecycle/handler/compose/util/ComposeLifecycleUtils.kt
> +    lifecycleViewModelStoreOwner.cached(lifecycleListener)
캐싱 로직은 side-effect 안으로 넣어줘서 실행을 최소화 시키는게 좋지 않을까 싶네요.

2023-02-11 13:56 UTC, SeongUgJung commented on _lifecycle-handler/lifecycle-handler-impl/src/main/java/io/androidalatan/lifecycle/handler/store/LifecycleViewModelStoreOwnerImpl.kt
> +        synchronized(this) {
dagger 의 lazy-loading 에서 구현된 double-check 를 모사해서 다음과 같이 구현되었으면 합니다.

```kotlin
if (key == null || cached.containsKey(key)) {
  synchronized(this) { /*기존 전체 로직*/ }
}
```

2023-02-11 13:59 UTC, SeongUgJung commented on _lifecycle-handler/lifecycle-handler-impl/src/main/java/io/androidalatan/lifecycle/handler/store/LifecycleViewModelStoreOwnerImpl.kt
> +        synchronized(this) {
https://github.com/google/dagger/blob/b5990a0641a7860b760aa9055b90a99d06186af6/java/dagger/internal/DoubleCheck.java 다음을 참고해주세요.

2023-02-25 06:17 UTC, SeongUgJung approved these changes

2023-02-25 06:19 UTC, taehwandev commented on _lifecycle-handler/lifecycle-handler-impl/src/main/java/io/androidalatan/lifecycle/handler/store/LifecycleViewModelStoreOwnerImpl.kt
> +                cached.remove(key)
👍 앗 제가 잊어버린 사이에...

2023-02-25 12:22 UTC, merged